apiVersion: v1
kind: Pod
metadata:
  name: stress
  namespace: k8sbook
spec:
  containers:
  - name: main
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "1G", "--vm-hang", "1"]
